
services:
  backend:
    build: ./backend
    ports:
      - "8082:8082"
    depends_on:
      - python-api

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  python-api:
    build: ./data-analysis-api
    ports:
      - "8000:8000"
